let num1 = 10;
let num2 = 5;
console.log("First number is: "+num1);
console.log("Second number is: "+num2);
let addnum = num1 + num2;
let subnum = num1 - num2;
let mulnum = num1 * num2;
let divnum = num1 / num2;
let pow = Math.pow(num1,num2);
console.log("If we add "+num1+" and "+num2+", the total will be = "+addnum);
console.log("If we subtract "+num1+" and "+num2+", the total will be = "+subnum);
console.log("If we multiply "+num1+" and "+num2+", the total will be = "+mulnum);
console.log("If we divide "+num1+" and "+num2+", the total will be = "+divnum);
console.log("The power of "+num1+", is "+pow);